### ISSUE TITLE
유저 이름 지우기 오류

### ISSUE THREAD

**Issue by kwag93** [rkskekzzz/blockcalendar#27]
컴퓨터 기준으로 왼쪽으로 드래그 후 쭉 가서 마우스 클릭을 놓으면 리스트는 꺼지는데 휴지통 아이콘 표시가 남아있어요!

왼쪽으로 땡겨서 휴지통 아이콘이 나왔을때 연속으로 빠르게 2번 누르면 한번에 두 유저가 지워져요!

모두 사파리 기준입니다

**Comment by rkskekzzz** [comment]
- [ ]  드래그 후 클릭을 놓으면 휴지통 아이콘 남아있음
- [ ]  2번 빠르게 누르면 두 유저가 지워짐
